### PR TITLE
Add Pickler.lazily

### PR DESCRIPTION
**Pull request by japgolly**
I needed this for a complex recursive case.

### CODE REVIEW

**Comment by ochrons** [comment]
Do you wanna update the documentation to show an example where this would be needed?

**Comment by japgolly** [comment]
The place I needed it is pretty big - I can't paste that. Maybe can use the `Tree` example instead?...

**Comment by ochrons** [comment]
Yeah, the simplest possible example is always good. As long as it's something that really needs the `lazily` function.

**Comment by japgolly** [comment]
Hehe, so not a lazy version of `UnitPickler` then? :grinning:

**Comment by japgolly** [comment]
I don't think I can come up with a reasonable example. I didn't think of this before but if you only access other picklers in the pickle/unpickle functions, then (because they are functions meaning their bodies are non-strict) `lazy val`s suffice without any problem.

In my case, due to some infrastructure I have that is important for other reasons, I need a Pickler strictly but due to its relationships it needs to be lazy internally else I get a StackOverflow.

**Comment by ochrons** [comment]
Ok, maybe then just describing in what kind of situation it would be needed. Because if this is something very specific to your use case only, then perhaps it shouldn't be in the library?

**Comment by japgolly** [comment]
Yeah, after trying to recreate it with `Tree` and `Cons` I realise now that my circumstances are super rare. My situation is that I have a typeclass factory for a crazy complex collection of intertwined structures. For 99.9999% of cases `lazy val` is going to be fine. I'm happy for the PR to be cancelled.

**Comment by ochrons** [comment]
Ok, let's leave it out then.

**Pull request closed without merging**
